on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push_package:
    name: 梱包の備立と押し込み
    runs-on: ubuntu-latest
    steps:
      - name: 倉庫から出納
        uses: actions/checkout@v2
      - name: GitHub Packagesを押し込む
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/image
          tag_with_ref: true
