name: 自動Docker像作成

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push-package:
    name: 梱包の備立と押し込み
    runs-on: ubuntu-latest
    outputs:
      usr_rep: ${{ steps.getusrrep.outputs.usr_rep }}
    steps:
      -
        name: 倉庫から出納
        uses: actions/checkout@v2
      -
        name: 準備
        id: prep
        run: |
          echo "::set-output name=username::$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
          #echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.event.after }})"
          echo "::set-output name=tag::$(expr '${{ github.ref }}' : 'refs/tags/\(v.*\)')"
      -
        uses: docker/setup-buildx-action@v1
      -
        name: ghcr.ioに録入り
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Docker像を備立しGitHub Packagesに押し込む
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ steps.prep.outputs.username }}/image:${{ steps.prep.outputs.tag }}
