name: 自動Docker像作成

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-package:
    name: 梱包の備立と押し込み
    runs-on: ubuntu-latest
    outputs:
      usr_rep: ${{ steps.getusrrep.outputs.usr_rep }}
    steps:
      - id: getusrrep
        run: |
          echo "::set-output name=usr_rep::$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
      - name: 倉庫から出納
        uses: actions/checkout@v2
      - name: Docker Buildxを設定
        uses: docker/setup-buildx-action@v1
      - name: GitHub Dockerに録入り
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker像を備立しGitHub Packagesに押し込む
        uses: docker/build-push-action@v2
        with:
          tags: docker.pkg.github.com/${{ steps.getusrrep.outputs.usr_rep }}/image:latest
          push: true
