name: 自動Docker像作成

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-package:
    name: 梱包の備立と押し込み
    runs-on: ubuntu-latest
    outputs:
      usr_rep: ${{ steps.getusrrep.outputs.usr_rep }}
    steps:
      - name: 準備
        id: prep
        run: |
          echo "::set-output name=repository::$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=tag::$(expr '${{ github.ref }}' : 'refs/tags/\(v.*\)')"
      - name: 倉庫から出納
        uses: actions/checkout@v2
      - name: Docker像を備立しGitHub Packagesに押し込む
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ steps.prep.outputs.repository }}/image:${{ steps.prep.outputs.tag }}
          push: true
