name: 自動Docker像作成

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-package:
    name: 梱包の備立と押し込み
    runs-on: ubuntu-latest
    outputs:
      usr_rep: ${{ steps.getusrrep.outputs.usr_rep }}
    steps:
      - name: 準備
        id: prep
        run: |
          echo "::set-output name=username::$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=tag::$(expr '${{ github.ref }}' : 'refs/tags/\(v.*\)')"
      - name: 倉庫から出納
        uses: actions/checkout@v2
      - name: Docker Buildxを設定
        uses: docker/setup-buildx-action@v1
      - name: GitHub Dockerに録入り
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker像を備立しGitHub Packagesに押し込む
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/${{ steps.prep.outputs.username }}/image:${{ steps.prep.outputs.tag }}
          push: true
