name: 自動Docker像作成

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push-package:
    name: 梱包の備立と押し込み
    runs-on: ubuntu-latest
    outputs:
      usr_rep: ${{ steps.getusrrep.outputs.usr_rep }}
    steps:
      -
        name: 倉庫から出納
        uses: actions/checkout@3
      -
        name: 準備
        id: prep
        run: |
          echo "username=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "changelog=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_OUTPUT
          echo "version=$(expr '${{ github.ref }}' : 'refs/tags/\(v.*\)')" >> $GITHUB_OUTPUT
      -
        uses: docker/setup-buildx-action@v2
      -
        name: ghcr.ioに録入り
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker像を備立しGitHub Packagesに押し込む
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.prep.outputs.username }}/image:${{ steps.prep.outputs.version }}
            ghcr.io/${{ steps.prep.outputs.username }}/image:latest
          labels: org.opencontainers.image.description=${{ steps.prep.outputs.changelog }}
